#!/usr/bin/env sh

source "$HOME/.config/colors.sh"

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa
#

# global settings
yabai -m config \
  mouse_follows_focus off \
  focus_follows_mouse off \
  window_origin_display default \
  window_placement second_child \
  window_zoom_persist off \
  window_shadow on \
  window_animation_duration 0.0 \
  window_animation_frame_rate 120 \
  window_opacity_duration 0.0 \
  active_window_opacity 1.0 \
  normal_window_opacity 1.0 \
  window_opacity off \
  insert_feedback_color 0xffd75f5f \
  split_ratio 0.50 \
  split_type auto \
  auto_balance off \
  top_padding 11 \
  bottom_padding 11 \
  left_padding 11 \
  right_padding 11 \
  window_gap 11 \
  layout bsp \
  mouse_modifier fn \
  mouse_action1 move \
  mouse_action2 resize \
  mouse_drop_action swap \
  external_bar all:36:0

yabai -m rule --add app="^(System Settings|System Information|Activity Monitor|FaceTime|Screen Sharing|Calculator|Stickies|TinkerTool|Progressive Downloader|Transmission|Airflow)$" manage=off

yabai -m signal --add event=window_created action="sketchybar -m --trigger window_change &> /dev/null"
yabai -m signal --add event=window_destroyed action="sketchybar -m --trigger window_change &> /dev/null"

echo "yabai configuration loaded.."

# disable specific apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" manage=off
yabai -m rule --add app="^QuickTime Player$" manage=off
yabai -m rule --add app="^Python$" manage=off
yabai -m rule --add app="^iScreen Shoter$" manage=off
yabai -m rule --add app="^Easy CSV Editor$" manage=off
yabai -m rule --add app="^AnyDesk$" manage=off
yabai -m rule --add app="^LINE$" manage=off
yabai -m rule --add app="^VNC Viewer$" manage=off
yabai -m rule --add app="^Mousecape$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^TapRecord$" manage=off
yabai -m rule --add title="Figure 1" manage=off
yabai -m rule --add title="Figure 2" manage=off
yabai -m rule --add title="Figure 3" manage=off
yabai -m rule --add title="Figure 4" manage=off
yabai -m rule --add title="Figure 5" manage=off
yabai -m rule --add title="Subplot configuration tool" manage=off
# borders active_color=0xffe1e3e4 enactive_color=0xff494d64 width=5.0 &
